kind: pipeline
name: default

steps:
  - name: build test image
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /go/test/
    commands:
      - docker build --no-cache -t cookiecutter-python-tests -f Dockerfile.tests .
